#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTHD="$(mktemp -d)"
XAUTH="$XAUTHD/xauth"

xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

if [ ! -d "${HOME}/.javafox/" ]; then
  mkdir -p "${HOME}/.javafox"
  mkdir -p "${HOME}/.javafox/.mozilla"
  mkdir -p "${HOME}/.javafox/.java/deployment/security"
  touch "${HOME}/.javafox/.java/deployment/security/exception.sites"
fi

docker run --rm --net=host -v $XSOCK:$XSOCK -v $XAUTHD:$XAUTHD -e XAUTHORITY=$XAUTH \
       -e DISPLAY=$DISPLAY \
       -v "${HOME}/.javafox/.java:/home/ffuser/.java" -v "${HOME}/.javafox/.mozilla:/home/ffuser/.mozilla" javafox $@

rm -rf $XAUTHD
