#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTHD="$(mktemp -d)"
XAUTH="$XAUTHD/xauth"

BASE="${HOME}/.javafox"
me=$(basename $0)
case $me in
    firefox-*)
        IMAGE=${me/-/:}
        BASE="${BASE}/instance/${me}"
        ;;
    *)
        IMAGE=javafox ;;
esac

# xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

xauth extract $XAUTH $DISPLAY

mkdir -p "${BASE}/.mozilla"
chmod 1777 "${BASE}/.mozilla"
mkdir -p "${BASE}/.java/deployment/security"
touch "${BASE}/.java/deployment/security/exception.sites"

docker run -ti --rm --net=host -v $XSOCK:$XSOCK -v $XAUTHD:$XAUTHD -e XAUTHORITY=$XAUTH \
       -e DISPLAY=$DISPLAY \
       -v "${BASE}/.java:/home/ffuser/.java" -v "${BASE}/.mozilla:/home/ffuser/.mozilla" ${IMAGE} "$@"

rm -rf $XAUTHD
