#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH="$(mktemp)"

xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

sudo docker run -i -t -v $XSOCK -v $XAUTH -e XAUTHORITY=$XAUTH firefox /usr/bin/firefox
